POST http://localhost:3001/api/books
Content-Type: application/json

{
    "title" : "Vạn Lý Trường Thành",
    "price" : 12.5,
    "authorId" : 10
}

###
DELETE http://localhost:3001/api/books/2
Content-Type: application/json

###
PUT http://localhost:3001/api/books/4
Content-Type: application/json

{
    "title" : "Vạn Lý Nhật Thành",
    "price" : 12.5,
    "authorId" : 3
}

###
GET http://localhost:3001/api/books
Content-Type: application/json


###
GET http://localhost:3001/api/books/4
Content-Type: application/json

{
    "name" : "Minhh"
}